version: 2
project_name: speedtest-exporter

builds:
  - id: speedtest-exporter
    main: ./src
    binary: speedtest-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Tag }}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: release-archives
    ids: [speedtest-exporter]
    formats: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_checksums.txt'

dockers_v2:
  - dockerfile: goreleaser.dockerfile
    images:
      - ghcr.io/adityathebe/speedtest-exporter
    tags:
      - 'v{{ .Version }}'
      - '{{ if not .IsNightly }}latest{{ end }}'
    build_args:
      VERSION: '{{ .Tag }}'
    labels:
      'org.opencontainers.image.created': '{{.Date}}'
      'org.opencontainers.image.name': '{{.ProjectName}}'
      'org.opencontainers.image.revision': '{{.FullCommit}}'
      'org.opencontainers.image.version': '{{.Version}}'
      'org.opencontainers.image.source': '{{.GitURL}}'
    platforms:
      - linux/amd64
      - linux/arm64
